"""Tests for the _build_info.py fallback pattern in build_mode.

When the build script writes ``src/utils/_build_info.py`` with
``IS_PORTABLE = True``, ``build_mode.py``'s try/except import picks
that up. When the file isn't present (the default repo state),
``IS_PORTABLE`` falls back to ``False``.

This test reloads the modules so one test process can verify both
states. Production code only ever sees one or the other (decided at
import time when the app launches).
"""
from __future__ import annotations

import importlib
import sys
from pathlib import Path

import pytest

pytestmark = pytest.mark.unit


@pytest.fixture
def build_info_module_cleanup():
    """Wipe any cached `src.utils._build_info` from sys.modules so the
    next import re-evaluates the disk state. Also nukes any temp file
    we wrote to ``src/utils/_build_info.py`` during the test."""
    repo_root = Path(__file__).resolve().parent.parent
    build_info_path = repo_root / "src" / "utils" / "_build_info.py"
    # Save original state (should not exist in the repo).
    original_existed = build_info_path.exists()
    original_content = build_info_path.read_text(encoding="utf-8") if original_existed else None

    # Drop cached imports so subsequent imports re-read disk.
    for mod_name in ("src.utils._build_info", "src.utils.build_mode"):
        sys.modules.pop(mod_name, None)

    yield build_info_path

    # Cleanup: restore original (or remove the temp file we created).
    if original_existed:
        build_info_path.write_text(original_content, encoding="utf-8")
    else:
        build_info_path.unlink(missing_ok=True)
    # Drop again so subsequent tests see the post-cleanup state.
    for mod_name in ("src.utils._build_info", "src.utils.build_mode"):
        sys.modules.pop(mod_name, None)


def test_default_when_build_info_missing(build_info_module_cleanup):
    """No ``_build_info.py`` on disk → IS_PORTABLE defaults to False.
    This is the default repo state and the standard build behavior."""
    assert not build_info_module_cleanup.exists(), (
        "_build_info.py should not exist in a clean repo — if this fires, "
        "an interrupted build left it behind. Remove it manually."
    )

    build_mode = importlib.import_module("src.utils.build_mode")
    assert build_mode.IS_PORTABLE is False


def test_portable_when_build_info_sets_true(build_info_module_cleanup):
    """``_build_info.py`` with IS_PORTABLE=True is written by
    ``build_exe.py --portable`` before PyInstaller bundles the source
    tree. After import, ``build_mode.IS_PORTABLE`` should reflect that."""
    build_info_module_cleanup.write_text(
        '"""Generated by build_exe.py for testing."""\n'
        'IS_PORTABLE: bool = True\n',
        encoding="utf-8",
    )

    build_mode = importlib.import_module("src.utils.build_mode")
    assert build_mode.IS_PORTABLE is True


def test_explicit_false_in_build_info_also_works(build_info_module_cleanup):
    """``_build_info.py`` could in principle be written with
    IS_PORTABLE=False (e.g. a CI matrix that produces both flavors and
    wants to be explicit). Confirm it's honored — no quirky truthy
    coercion."""
    build_info_module_cleanup.write_text(
        '"""Generated by build_exe.py for testing."""\n'
        'IS_PORTABLE: bool = False\n',
        encoding="utf-8",
    )

    build_mode = importlib.import_module("src.utils.build_mode")
    assert build_mode.IS_PORTABLE is False
